#!/bin/sh
# Tiny Password Vault
# See LICENSE file for licensing and copyright info.
HELP_MESSAGE="\
Tiny Password Vault:
    Get (-g) a password from a file (-f):
        tpv -g -f filename

    Add (-a) a password to a file (-f):
        tpv -a -f filename

    Passwords are stored in this format:
        for: website_name
        pwd my_password
        ...
        and_so_on and_so_forth

        for: <section name>
        <field name> <value name>
        ...
        <field name> <value name>

        ...

    To encrypt/decrypt the entire file:
        tpv -d -f filename
        tpv -c -f filename
"
# Handle the arguments: ===============================================
INVALID_ARGUMENTS=0
FILENAME=""
OPTION=""
ARG_TYPE="option"
[ "$#" = "0" ] && INVALID_ARGUMENTS=1     # No args, error out.
[ "$1" = "-h" ] && INVALID_ARGUMENTS=1    # Help option, error out.
[ "$1" = "-help" ] && INVALID_ARGUMENTS=1 # Help option, error out.
for i in $@; do
    [ "$ARG_TYPE" = "file" ] && FILENAME="$i" && ARG_TYPE="option"
    [ "$i" = "-f" ] && ARG_TYPE="file"
    [ "$i" = "-g" ] && OPTION="get"
    [ "$i" = "-a" ] && OPTION="add"
    [ "$i" = "-d" ] && OPTION="decrypt"
    [ "$i" = "-c" ] && OPTION="encrypt"
done
# Print the help message if arguments are invalid:
[ "$OPTION"   = "" ] && INVALID_ARGUMENTS=1
[ "$FILENAME" = "" ] && INVALID_ARGUMENTS=1
[ "$OPTION" = "get" ] && [ ! -f "$FILENAME" ] && INVALID_ARGUMENTS=1
[ "$OPTION" = "add" ] && [ "$FILENAME" = "" ] && INVALID_ARGUMENTS=1
[ "$INVALID_ARGUMENTS" = "1" ] && printf "$HELP_MESSAGE" && exit 1
#-----------------------------------------------------------------------

# Whole file encryption/decryption:
[ "$OPTION" = "decrypt" ] && gpg -d "$FILENAME" > tmp && mv tmp "$FILENAME" && exit 0
[ "$OPTION" = "encrypt" ] && gpg -c "$FILENAME" && mv "$FILENAME.gpg" "$FILENAME" && exit 0

# Add a new entry to the file: =========================================
if [ "$OPTION" = "add" ]; then
    [ ! -f "$FILENAME" ] && printf "New pwd file: $FILENAME\n" # New file.
    [ -f "$FILENAME" ] && DATA="$(gpg -d "$FILENAME")" # Decrypt file.
    printf "New entry:\n"
    read -p "for: " NEW_FOR
    stty -echo && read -p "pwd: " NEW_PWD && stty echo # Don't show the pwd!
    NEW_FIELDS=""
    INPUT=""
    printf '\nField format: <field_name> <field_value>\n(q to quit)\n'
    while true; do 
        read -p 'New field: ' INPUT
        [ "$INPUT" = "q" ] && break
        NEW_FIELDS="$(printf "$NEW_FIELDS\n$INPUT")"
    done
    printf "\n"
    NEW_ENTRY="$(printf "for: $NEW_FOR$NEW_FIELDS\npwd: $NEW_PWD")"
    # Insert the new entry to the encrypted file:
    DATA="$(printf "$DATA\n\n$NEW_ENTRY")"
    printf "$DATA" | gpg -c > "$FILENAME"
fi
#------------------------------------------------------------------------

# Decrypt the passwords file into DATA, stripped of comments. ===========
if [ "$OPTION" = "get" ]; then
    DATA="$(gpg -d "$FILENAME" | sed "/^#/d")"
    # Choose a section to retrieve info from:
    SECTION="$(echo "$DATA" | grep '^for:' | cut -d ' ' -f 2- | dmenu -l 20)"
    SECTION_START="$(echo "$DATA" | grep -n "for: $SECTION" | cut -d ':' -f1 | head -n 1)"
    # Select the desired field (username, password, ect).
    FIELD="$(echo "$DATA" | sed -n "$SECTION_START,/^for: /p" | sed '/^\s*$/d' | sed '/^for:/d' | cut -d ' ' -f 1 | dmenu -l 20)"

    # Copy the selected field.
    echo "$DATA" |
        sed -n "$SECTION_START,/^for: /p" |
        grep "^$FIELD" | head -n 1 |
        cut -d ' ' -f 2- |
        xclip -r -selection 'clipboard'
fi
#-------------------------------------------------------------------------
# Make sure the unencrypted text doesn't stick around.
DATA=""; FIELD=""; SECTION=""; SECTION_START=""
